//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Slot
    {
        public int Slot_ID { get; set; }
        public int Creation_Date { get; set; }
        public string Slot_Time { get; set; }
        public int Booking_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
